import Link from "next/link";

import "./globals.css";

import Control from "@/components/Control";

export const metadata = {
  title: "Web tutorials",
  description: "Generated by twgu",
};

export default async function RootLayout({ children }) {
  const options = { cache: "no-store" };
  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + "/topics", options);
  const topics = await resp.json();

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
